name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools_scm
      - name: Debug setuptools_scm version
        run: |
          python -c "from setuptools_scm import get_version; print(f'Version from setuptools_scm: {get_version()}')"
      - name: Clean build artifacts
        run: |
          rm -rf build/ dist/ *.egg-info/
      - name: Build distribution
        run: |
          python -m build --verbose
      - name: Check built package version
        run: |
          python -c "
          import pkg_resources
          import glob
          wheel_files = glob.glob('dist/*.whl')
          if wheel_files:
              print(f'Built wheel: {wheel_files[0]}')
          else:
              print('No wheel files found')
          "
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
